/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class at_libtester_MyNativeClass */

#ifndef _Included_at_libtester_MyNativeClass
#define _Included_at_libtester_MyNativeClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     at_libtester_MyNativeClass
 * Method:    myNativeMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_at_libtester_MyNativeClass_myNativeMethod
  (JNIEnv *, jclass);

/*
 * Class:     at_libtester_MyNativeClass
 * Method:    hello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_at_libtester_MyNativeClass_hello
  (JNIEnv *, jclass);

/*
 * Class:     at_libtester_MyNativeClass
 * Method:    hi
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_at_libtester_MyNativeClass_hi
  (JNIEnv *, jclass, jstring);

/*
 * Class:     at_libtester_MyNativeClass
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_at_libtester_MyNativeClass_add
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
